### PR TITLE
Javascript packaging with typings

### PR DESCRIPTION
**Pull request by christphe**
Hi,

My application is built with rollup and the current packaging didn't work.
A npm package should reference a javascript file so it should reference the .js file and provide typings.

I hope it still works with your projects

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
Hi!

Thanks for your contribution!
I'll test it until tomorrow, and if it's good - I'll merge it and upgrade the version.

Maybe another contributor like @Stoom can check this out today and comment if it's disturbing his working-projects with the packager.


Stay safe!

**Comment by Stoom** [comment]
In general it's good practice to commit the lock for so that new versions of dependencies do not break things.  Moment is just a moment yesterday and the lock for was the only thing protecting our product at work.

**Comment by davidmeirlevy** [comment]
@christphe , @Stoom is right, can you please un-ignore the yarn.lock file?

@Stoom do you have any other concerns about this update? since you probably using this package, and you won't need it to break.

**Comment by Stoom** [comment]
It looks fine.  I'm a little unsure of what the problem was with the typing as it was picking up all of the typing before for me, but it doesn't look like this should break anything.  I haven't tested it out as I've been pulled away from my project that uses this.

**Comment by christphe** [comment]
I can remove it from the ignore files, do you want me to commit it too ?

**Comment by davidmeirlevy** [comment]
@christphe  Yes, please. thanks.

@Stoom It adds declaration files, so also people that use js can import the package directly, without specifying the "dist" folder, and still enjoy the typings of the project in their IDEs.

**Comment by davidmeirlevy** [comment]
@christphe merged and published to version 1.0.16

**Pull request merged**
