### PR TITLE
WIP dropped composition API, adjustements to Vue3

### PR DESCRIPTION
**Pull request by Valian**
Related to https://github.com/greenpress/vuex-composition-helpers/issues/25

Still WIP, some tests are failing when comparing rendered templates

Also, I had to add `{immediate: true}` to all watch() calls in tests, because it looked like the right thing to do. Is it correct @davidmeirlevy?

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
You cannot change the test in order to make the new version work.
Thousands of weekly downloads in NPM use this library exactly as it is now, and it should work exactly the same for the next version of vue.

**Comment by Valian** [comment]
@davidmeirlevy so you would like this library to be compatible with both vue 2 and 3? I understand dropping support for vue 2 is not an option, but maybe releasing it with a separate tag, like `vuex-composition-helpers-next`  would do?

**Comment by davidmeirlevy** [comment]
we can make the same package but with a @next tag on the version, like: `npm i vuex-composition-helpers@2.0.0-next`.
but the behavior should be the same, so everything that worked without `immediate: true` should remain the same.

**Comment by Valian** [comment]
I can try to do that, but honestly I don't understand that behaviour. It looks like currently watch is triggered as soon as it's declared, even if there is no change. Test snippet:

```javascript
                it('should trigger a watcher according a getter change', async () => {
			const watcher = jest.fn();
			const store = new Vuex.Store({
				state: {val: 'test-demo' + Math.random()},
				getters: {testGetter: (state) => state.val}
			});

			const wrapper = shallowMount({
					template: '<div>{{val}}</div>',
					setup() {
						const {testGetter} = useGetters(store, ['testGetter']);
						watch(testGetter, watcher);
						return {val: testGetter}
					}
				},
				{localVue}
			);
                         // <--- This line, it looks like it was already triggered without change
			expect(watcher).toBeCalledTimes(1); 

			store.state.val = 'new value' + Math.random();
			expect(watcher).toBeCalledTimes(1);

			// wait for rendering
			await wrapper.vm.$nextTick();

			expect(watcher).toBeCalledTimes(2);
		});
```

This behaviour is against the definition of `watch` - https://vuejs.org/v2/api/#vm-watch. Without `immediate: true` it shouldn't be called. Do you see the problem? 

I think I'm having that issue because package.json is using a very old composition-api: 0.4.0. Version 0.6.0 [fixed that](https://github.com/vuejs/composition-api/releases/tag/v0.6.0). Upgrading composition api to the newest version on the master branch is probably a good idea before trying to make this package work with Vue 3.

**Comment by davidmeirlevy** [comment]
You probably right..
Upgrading vue2 composition api to see how it works on upgraded version is mandatory too.

**Comment by davidmeirlevy** [comment]
I already made "next" branch (and also "next" tag for the npm package) to use with vue3.

**Pull request closed without merging**
