### PR TITLE
feat: add inline namespace for global helpers

### LINKED ISSUE #57: [Feature Request] In-place namespaces
Would be nice to have "in-place" namespaces, similar to what happens with [`vuex` mappers](https://vuex.vuejs.org/api/#component-binding-helpers).

```javascript
import { useGetters } from 'vuex-composition-helpers'

export default {
  setup() {
    const { one, two } = useGetters('my/long/name/space', ['one', 'two'])
    const { uno, dos } = useGetters('my/other/thing', ['uno', 'dos'])
    return { one, two, uno, dos }
  }
}
```

### PR DESCRIPTION
**Pull request by nolde**
Resolves #57

All tests are passing.

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
Looks great.
Can you add more tests that will cover the new API you added?

**Comment by nolde** [comment]
Sure!

You had tests for `map`, `store+map`, and `store+namespace+map` (the ones using `createNamespacedHelpers`), so those should still be covered by the existing ones.

I will add some more for `namespace+map`, which are the only ones missing.

**Comment by nolde** [comment]
Done!

**Comment by nolde** [comment]
Anything else you need from me on this one, @davidmeirlevy ?

**Review by davidmeirlevy — APPROVED** [review]

**Comment by davidmeirlevy** [comment]
@nolde nothing, that's awesome!
I'll publish the new version today.

also, if you can add this ability into the cloned branch of the #55  branch, that will be awesome too (this branch is having this package working for vue3).

**Comment by nolde** [comment]
Sure,, will take a look at that!

Might take a while longer though, with holidays coming up.

Thanks for merging!

**Pull request merged**
