### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by udisun**
removed peer dependencies

### CODE REVIEW

**Comment by udisun** [comment]
tested and worked

**Review by davidmeirlevy — APPROVED** [review]

**Comment by davidmeirlevy** [comment]
Thanks! I'll publish it soon.

**Comment by bissolli** [comment]
@davidmeirlevy would mind publishing the package? I really want to test this lib, but due to the peerDeps I can't install on my project.

Thanks!

**Comment by davidmeirlevy** [comment]
Done. vuex-composition-helpers@1.0.23
@bissolli sorry for the delay.

**Pull request merged**
